In [1]:
import numpy as np

PROBLEMS 1
making a tensor

In [8]:
T = np.array([
    [[23,50],[7,12]],
    [[57,67],[99,43]],
    [[75,21],[57,12]],
    [[87,26],[18,84]]
])
T

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

PROBLEMS 2
perkalian matrix

In [14]:
A = np.array([
    [23,50,19],
    [7,12,109],
    [57,67,98]
])
B = np.array([
    17,22,19
])

print(A)
print(B)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
[17 22 19]


In [15]:
AxB = A*B
print(A*B)

[[ 391 1100  361]
 [ 119  264 2071]
 [ 969 1474 1862]]


PROBLEMS 3
TRANSPOSE,DETERMINAN, and inverse

In [17]:
C = np.array([
    [23,50,19],
    [7,12,109],
    [57,67,98]
])

print(C)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]


In [19]:
trans = C.T
print(trans)

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]


In [22]:
from numpy.linalg import det

det = det(C)
print(det)

131344.0000000002


In [23]:
from numpy.linalg import inv

invers = inv(C)
print(invers)

[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
